@node Considerações finais
@chapter Considerações finais

@node O trabalho 
@section O trabalho
O processo de criação dos servidores @acronym{SMTP} tomou
mais ou menos duas semanas. A escrita dos códigos, entretanto,
aconteceu de maneira gradual.

O grupo, de início, não compreendeu o objetivo final do projeto,
uma vez que o enunciado em si não estava ``solidificado'' o
bastante no primeiro momento em que foi passado. Assim que
o projeto fora ``oficializado'', foi possível entender como
o processo deveria ocorrer. É recomendado ao professor
que haja uma listagem de todos os requisitos do projeto na primeira vez que
for passado um enunciado como esse.

Contanto, o desenvolvimento do projeto, bem como sua documentação
fora divertida e permitiu um aprendizado melhor do protocolo
@acronym{SMTP}, gerando a oportunidade de compreender todo
o processo enquanto era praticada a programação deste.



