\input texinfo
@setfilename doc_smtp
@documentencoding UTF-8
@documentlanguage pt_BR
@settitle @acronym{SMTP} @acronym{SMTP} Manual

@copying
Nenhum direito reservado.
@end copying

@titlepage
@title @acronym{SMTP} @acronym{SMTP} (Servidor Mega Tecnologico Perfeito @acronym{SMTP})
@author Leon F. Bellini (22218002-8)
@author Gulherme O. Sampaio (22218007-7)
@author Felipe Maciel de Sousa (22218042-4)
@page
@vskip 0pt plus 1fill
@insertcopying
@end titlepage

@ifnottex
@node Top
@top Topo
Seja bem vindo ao manual geral do @acronym{SMTP} @acronym{SMTP}, um @emph{script} do tipo @emph{wrapper}
o qual executa todos os servidores @acronym{SMTP} definidos pelo usuario, bem como suas respectivas
portas e seus ``pseudo-domínios''.
@end ifnottex

@menu
* Introdução:: Requerimentos e como executar o @emph{script}.
* Mandando um e-mail:: Procedimento geral para enviar um e-mail
* Considerações finais:: O trabalho e as dificuldades encontradas
@end menu

@include introducao.texinfo
@include mandando.texinfo
@include consideracoes.texinfo
@bye

